### ISSUE TITLE
[BUG] Key error in student unet

### ISSUE THREAD

**Issue by alfredplpl** [segmind/SSD-1B#3]
```bash
Resolving data files: 100%|█████████████████████████████████████████████████████| 2363/2363 [00:00<00:00, 519969.59it/s]
10/27/2023 13:37:22 - INFO - __main__ - ***** Running training *****
10/27/2023 13:37:22 - INFO - __main__ -   Num examples = 2362
10/27/2023 13:37:22 - INFO - __main__ -   Num Epochs = 100
10/27/2023 13:37:22 - INFO - __main__ -   Instantaneous batch size per device = 1
10/27/2023 13:37:22 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 128
10/27/2023 13:37:22 - INFO - __main__ -   Gradient Accumulation steps = 128
10/27/2023 13:37:22 - INFO - __main__ -   Total optimization steps = 1900
Steps:   0%|                                                                                   | 0/1900 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/my_raid/github/SSD-1B/distill_sdxl.py", line 1270, in <module>
    main(args)
  File "/mnt/my_raid/github/SSD-1B/distill_sdxl.py", line 1076, in main
    loss_features=loss_features+F.mse_loss(KD_teacher['m'],KD_student['mr0'])
KeyError: 'mr0'
Steps:   0%|                                                                                   | 0/1900 [00:01<?, ?it/s]
```

How do I fix it?
I comment it out.

Thanks in advance.

**Comment by alfredplpl** [comment]
should I use --snr_gamma option?
